apiVersion: v1

kind: Service

metadata:
  name: gemini-llm-service

spec:

  selector:
    app: gemini-llm

  ports:

    - protocol: TCP

      port: 80

      targetPort: 8000

  type: ClusterIP